// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: tts.proto

package ttspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 合成请求.
type SynthesizeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 要合成的纯净文本 (不含 <tags>).
	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	// 语气标签 (calm/warm/cheerful/... ), 空字符串表示不加语气控制.
	// Go 服务端会拼装 CosyVoice2 instruct2 指令.
	Tone string `protobuf:"bytes,2,opt,name=tone,proto3" json:"tone,omitempty"`
	// 设备 ID, 从 gRPC metadata 的 Authorization 头解析, 用于日志.
	// 不需要客户端显式传, 这里保留用于服务端日志关联.
	DeviceId string `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	// LLM 规划的语速倍率，服务端转换为供应商原生韵律指令；0 表示默认 1.0。
	SpeakingRate  float64 `protobuf:"fixed64,4,opt,name=speaking_rate,json=speakingRate,proto3" json:"speaking_rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SynthesizeRequest) Reset() {
	*x = SynthesizeRequest{}
	mi := &file_tts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SynthesizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SynthesizeRequest) ProtoMessage() {}

func (x *SynthesizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SynthesizeRequest.ProtoReflect.Descriptor instead.
func (*SynthesizeRequest) Descriptor() ([]byte, []int) {
	return file_tts_proto_rawDescGZIP(), []int{0}
}

func (x *SynthesizeRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SynthesizeRequest) GetTone() string {
	if x != nil {
		return x.Tone
	}
	return ""
}

func (x *SynthesizeRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *SynthesizeRequest) GetSpeakingRate() float64 {
	if x != nil {
		return x.SpeakingRate
	}
	return 0
}

// 非流式合成响应.
type SynthesizeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 完整 WAV 文件字节 (含 44 字节 WAV 头 + PCM16 数据).
	AudioData []byte `protobuf:"bytes,1,opt,name=audio_data,json=audioData,proto3" json:"audio_data,omitempty"`
	// 音频格式, 固定 "wav".
	AudioFormat   string `protobuf:"bytes,2,opt,name=audio_format,json=audioFormat,proto3" json:"audio_format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SynthesizeResponse) Reset() {
	*x = SynthesizeResponse{}
	mi := &file_tts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SynthesizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SynthesizeResponse) ProtoMessage() {}

func (x *SynthesizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SynthesizeResponse.ProtoReflect.Descriptor instead.
func (*SynthesizeResponse) Descriptor() ([]byte, []int) {
	return file_tts_proto_rawDescGZIP(), []int{1}
}

func (x *SynthesizeResponse) GetAudioData() []byte {
	if x != nil {
		return x.AudioData
	}
	return nil
}

func (x *SynthesizeResponse) GetAudioFormat() string {
	if x != nil {
		return x.AudioFormat
	}
	return ""
}

// 流式合成的一个数据块.
type AudioChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// PCM 数据块.
	// 第一个 chunk 是 44 字节 WAV 头 (dataSize=0), 后续 chunk 是裸 PCM16.
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// 采样率, 从 WAV 头解析. 客户端用它初始化 waveOut 设备.
	// 只在第一个 chunk (WAV 头) 中有意义, 后续 chunk 为 0.
	SampleRate    int32 `protobuf:"varint,2,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioChunk) Reset() {
	*x = AudioChunk{}
	mi := &file_tts_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioChunk) ProtoMessage() {}

func (x *AudioChunk) ProtoReflect() protoreflect.Message {
	mi := &file_tts_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioChunk.ProtoReflect.Descriptor instead.
func (*AudioChunk) Descriptor() ([]byte, []int) {
	return file_tts_proto_rawDescGZIP(), []int{2}
}

func (x *AudioChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AudioChunk) GetSampleRate() int32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

var File_tts_proto protoreflect.FileDescriptor

const file_tts_proto_rawDesc = "" +
	"\n" +
	"\ttts.proto\x12\vswallow.tts\"}\n" +
	"\x11SynthesizeRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x12\n" +
	"\x04tone\x18\x02 \x01(\tR\x04tone\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\x12#\n" +
	"\rspeaking_rate\x18\x04 \x01(\x01R\fspeakingRate\"V\n" +
	"\x12SynthesizeResponse\x12\x1d\n" +
	"\n" +
	"audio_data\x18\x01 \x01(\fR\taudioData\x12!\n" +
	"\faudio_format\x18\x02 \x01(\tR\vaudioFormat\"A\n" +
	"\n" +
	"AudioChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1f\n" +
	"\vsample_rate\x18\x02 \x01(\x05R\n" +
	"sampleRate2\xa3\x01\n" +
	"\x03TTS\x12M\n" +
	"\n" +
	"Synthesize\x12\x1e.swallow.tts.SynthesizeRequest\x1a\x1f.swallow.tts.SynthesizeResponse\x12M\n" +
	"\x10StreamSynthesize\x12\x1e.swallow.tts.SynthesizeRequest\x1a\x17.swallow.tts.AudioChunk0\x01B/Z-github.com/swallow-sun/swallow-go/proto;ttspbb\x06proto3"

var (
	file_tts_proto_rawDescOnce sync.Once
	file_tts_proto_rawDescData []byte
)

func file_tts_proto_rawDescGZIP() []byte {
	file_tts_proto_rawDescOnce.Do(func() {
		file_tts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tts_proto_rawDesc), len(file_tts_proto_rawDesc)))
	})
	return file_tts_proto_rawDescData
}

var file_tts_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_tts_proto_goTypes = []any{
	(*SynthesizeRequest)(nil),  // 0: swallow.tts.SynthesizeRequest
	(*SynthesizeResponse)(nil), // 1: swallow.tts.SynthesizeResponse
	(*AudioChunk)(nil),         // 2: swallow.tts.AudioChunk
}
var file_tts_proto_depIdxs = []int32{
	0, // 0: swallow.tts.TTS.Synthesize:input_type -> swallow.tts.SynthesizeRequest
	0, // 1: swallow.tts.TTS.StreamSynthesize:input_type -> swallow.tts.SynthesizeRequest
	1, // 2: swallow.tts.TTS.Synthesize:output_type -> swallow.tts.SynthesizeResponse
	2, // 3: swallow.tts.TTS.StreamSynthesize:output_type -> swallow.tts.AudioChunk
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tts_proto_init() }
func file_tts_proto_init() {
	if File_tts_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tts_proto_rawDesc), len(file_tts_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tts_proto_goTypes,
		DependencyIndexes: file_tts_proto_depIdxs,
		MessageInfos:      file_tts_proto_msgTypes,
	}.Build()
	File_tts_proto = out.File
	file_tts_proto_goTypes = nil
	file_tts_proto_depIdxs = nil
}
