// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: tts.proto

package ttspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TTS_Synthesize_FullMethodName       = "/swallow.tts.TTS/Synthesize"
	TTS_StreamSynthesize_FullMethodName = "/swallow.tts.TTS/StreamSynthesize"
)

// TTSClient is the client API for TTS service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TTS 服务: 流式和非流式语音合成.
// C++ 客户端通过 gRPC 调用, Go 服务端转发给 TTS provider (CosyVoice2/SiliconFlow).
type TTSClient interface {
	// 非流式合成: 一次性返回完整 WAV.
	Synthesize(ctx context.Context, in *SynthesizeRequest, opts ...grpc.CallOption) (*SynthesizeResponse, error)
	// 流式合成: 逐块返回 PCM 数据 (先 44 字节 WAV 头, 再逐块 PCM16).
	// 客户端边收边播放, 减少首包延迟.
	StreamSynthesize(ctx context.Context, in *SynthesizeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AudioChunk], error)
}

type tTSClient struct {
	cc grpc.ClientConnInterface
}

func NewTTSClient(cc grpc.ClientConnInterface) TTSClient {
	return &tTSClient{cc}
}

func (c *tTSClient) Synthesize(ctx context.Context, in *SynthesizeRequest, opts ...grpc.CallOption) (*SynthesizeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SynthesizeResponse)
	err := c.cc.Invoke(ctx, TTS_Synthesize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tTSClient) StreamSynthesize(ctx context.Context, in *SynthesizeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AudioChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TTS_ServiceDesc.Streams[0], TTS_StreamSynthesize_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SynthesizeRequest, AudioChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TTS_StreamSynthesizeClient = grpc.ServerStreamingClient[AudioChunk]

// TTSServer is the server API for TTS service.
// All implementations must embed UnimplementedTTSServer
// for forward compatibility.
//
// TTS 服务: 流式和非流式语音合成.
// C++ 客户端通过 gRPC 调用, Go 服务端转发给 TTS provider (CosyVoice2/SiliconFlow).
type TTSServer interface {
	// 非流式合成: 一次性返回完整 WAV.
	Synthesize(context.Context, *SynthesizeRequest) (*SynthesizeResponse, error)
	// 流式合成: 逐块返回 PCM 数据 (先 44 字节 WAV 头, 再逐块 PCM16).
	// 客户端边收边播放, 减少首包延迟.
	StreamSynthesize(*SynthesizeRequest, grpc.ServerStreamingServer[AudioChunk]) error
	mustEmbedUnimplementedTTSServer()
}

// UnimplementedTTSServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTTSServer struct{}

func (UnimplementedTTSServer) Synthesize(context.Context, *SynthesizeRequest) (*SynthesizeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Synthesize not implemented")
}
func (UnimplementedTTSServer) StreamSynthesize(*SynthesizeRequest, grpc.ServerStreamingServer[AudioChunk]) error {
	return status.Error(codes.Unimplemented, "method StreamSynthesize not implemented")
}
func (UnimplementedTTSServer) mustEmbedUnimplementedTTSServer() {}
func (UnimplementedTTSServer) testEmbeddedByValue()             {}

// UnsafeTTSServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TTSServer will
// result in compilation errors.
type UnsafeTTSServer interface {
	mustEmbedUnimplementedTTSServer()
}

func RegisterTTSServer(s grpc.ServiceRegistrar, srv TTSServer) {
	// If the following call panics, it indicates UnimplementedTTSServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TTS_ServiceDesc, srv)
}

func _TTS_Synthesize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SynthesizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TTSServer).Synthesize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TTS_Synthesize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TTSServer).Synthesize(ctx, req.(*SynthesizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TTS_StreamSynthesize_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SynthesizeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TTSServer).StreamSynthesize(m, &grpc.GenericServerStream[SynthesizeRequest, AudioChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TTS_StreamSynthesizeServer = grpc.ServerStreamingServer[AudioChunk]

// TTS_ServiceDesc is the grpc.ServiceDesc for TTS service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TTS_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "swallow.tts.TTS",
	HandlerType: (*TTSServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Synthesize",
			Handler:    _TTS_Synthesize_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamSynthesize",
			Handler:       _TTS_StreamSynthesize_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "tts.proto",
}
