// register.go 放 HTTP 路由注册逻辑.
//
// 做的事情:
//  1. 注册健康检查路由: GET /ping.
//  2. 注册对话 API 路由: POST /api/session, GET /api/history, POST /api/chat.
//  3. 路由对应的 handler 方法绑定在 deps 上, 共享同一份依赖.
package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"

	"github.com/swallow-sun/swallow-go/biz/handler"
)

// Register 注册所有业务路由.
// r 是 Hertz 的 HTTP 服务实例, 启动时由 main.go 创建好后传进来.
// deps 里面有 llm/memory/identity 等共享依赖, 启动时创建一次.
func Register(r *server.Hertz, deps *handler.Deps) {
	// 先调 Hertz 的 IDL 生成路由注册函数. 当前项目没用 IDL, 所以这里是空函数, 留作以后扩展用
	GeneratedRegister(r)

	// 健康检查
	// r.GET 是 Hertz 框架提供的路由注册方法, 意思是"注册一个 GET 请求的路由"
	// 第一个参数 "/ping" 是 URL 路径
	// 第二个参数 handler.Ping 是收到这个请求时要执行的 handler 函数
	// 浏览器或 curl 发 GET 请求到 http://localhost:端口/ping, 就会走 handler.Ping
	r.GET("/ping", handler.Ping)

	// 对话 API
	// r.Group 是 Hertz 框架提供的路由分组方法, 意思是"创建一个路由组, 下面所有路由都自动带上 /api 前缀"
	// 举个例子, 下面 api.POST("/session", ...) 实际注册的完整路径是 /api/session
	api := r.Group("/api")
	{
		// api.POST 是 Hertz 框架的路由注册方法, 意思是"注册一个 POST 请求的路由"
		// 完整路径是 /api/session, 用于创建一个新会话
		// deps.CreateSession 是 deps 上绑定的 handler 方法, 共享同一份 llm/memory/identity 依赖
		api.POST("/session", deps.CreateSession)
		// 完整路径是 /api/history, 用于查某个会话的历史消息
		// GET 请求, 参数通过 URL query 传, 比如 /api/history?session_id=xxx
		api.GET("/history", deps.GetHistory)
		// 完整路径是 /api/chat, 用于发消息跟 AI 对话
		// POST 请求, 参数通过 body 传, 支持 SSE 流式返回
		api.POST("/chat", deps.Chat)
	}
}

// GeneratedRegister registers routers generated by IDL.
// 这是 Hertz 脚手架自动生成的占位函数, 用来放 IDL(接口定义语言)生成的路由代码.
// 当前项目没用 IDL, 所以函数体是空的, 只保留了一行注释占位符, 方便以后扩展.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
}
